create database dw2;
use dw2;
create table Filme(id int AUTO_INCREMENT,title varchar(70),release_year int,language varchar(45),lenght int,rating double, PRIMARY KEY (id));
create table Receita(id int AUTO_INCREMENT,pais varchar(70),valor int,filmeId int, PRIMARY KEY (id), FOREIGN KEY (filmeId) REFERENCES Filme(id));
create table Ator(id int AUTO_INCREMENT, name varchar(70), artistic_name varchar(70), birth_date varchar(45), PRIMARY KEY (id) );
create table FilmeAtor(id int AUTO_INCREMENT, filmeId int NOT NULL, atorId int NOT NULL, PRIMARY KEY (id), Foreign Key (filmeId) References Filme(id), Foreign Key (atorId) References Ator(id));

INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('The Shawshank Redemption',1994,'Inglês',142,9.3);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('The Godfather',1972,'Inglês',175,9.2);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('The Godfather: Part II',1974,'Inglês',202,9);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('The Dark Knight',2008,'Inglês',152,9);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('12 Angry Men',1957,'Inglês',96,9);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Schindler\'s List',1993,'Inglês',195,8.9);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('The Lord of the Rings: The Return of the King',2003,'Inglês',201,8.9);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Pulp Fiction',1994,'Inglês',154,8.9);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Il buono, il brutto, il cattivo',1996,'Inglês',161,8.8);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('The Lord of the Rings: The Fellowship of the Ring',2001,'Inglês',178,8.8);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Fight Club',1999,'Inglês',139,8.8);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Forrest Gump',1994,'Inglês',142,8.8);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Inception',2010,'Inglês',148,8.8);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('The Lord of the Rings: The Two Towers',2002,'Inglês',179,8.7);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Star Wars: Episode V - The Empire Strikes Back',1980,'Inglês',124,8.7);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Matrix',1999,'Inglês',136,8.7);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Spider-Man: No Way Home',2021,'Inglês',148,8.6);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Goodfellas',1990,'Inglês',146,8.7);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('One Flew Over the Cuckoo\'s Nest',1975,'Inglês',133,8.7);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Shichinin no samurai',1954,'Japonês',207,8.6);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Se7en',1995,'Inglês',127,8.6);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('The Silence of the Lambs',1991,'Inglês',118,8.6);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('It\'s a Wonderful Life',1946,'Inglês',130,8.6);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('City of God',2002,'Inglês',130,8.6);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('La vita è bella',1997,'Italiano',114,8.6);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Saving Private Ryan',1998,'Inglês',169,8.6);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Star Wars: Episode IV - A New Hope',1977,'Inglês',121,8.6);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Interstellar',2014,'Inglês',169,8.6);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('Sen to Chihiro no kamikakushi',2001,'Japonês',125,8.6);
INSERT INTO Filme (title,release_Year,language,lenght,rating) VALUES ('The Green Mile',1999,'Inglês',189,8.6);

INSERT INTO Receita (pais, valor, filmeId) VALUES ('USA', 100000, 1);
INSERT INTO Ator (name, artistic_name, birth_date) VALUES ('Morgan Porterfield Freeman Jr.','Morgan Freeman','01/06/1937');
INSERT INTO FilmeAtor (filmeId, atorId) VALUES (1,1);