version: "3.7"

services:
  mysql:
    container_name: mysql
    image: meloana/inf21dw2g23:mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - my-network
    ports:
      - 3306:3306
  api:
    depends_on:
      - mysql
    container_name: api
    image: meloana/inf21dw2g23:api
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    networks:
      - my-network

  app:
    depends_on:
      - api
    container_name: app
    image: meloana/inf21dw2g23:app
    environment:
      NODE_ENV: production
    ports:
      - 5000:3000
    networks:
      - my-network

networks:
  my-network:
